# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b128add544cb4f12bbf958903fcbf40fa0e44b5e71f647340db0b022c9ab2f26c5a76278c2c8728f502132f111e0ba4d2dd1fa829bf431517dac46f5d85ccb88

test:
  secret_key_base: 1260a7056a20df1bd8400dc93784071c1da22a9ef84832ea50277ce06d48117e0d6685048046d529087f76735836f52c98ddac06f729c21900fa7e8f20767128

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
